CREATE TABLE PLAYER(
PID INTEGER PRIMARY KEY, 
PNAME VARCHAR2(20) NOT NULL,
RANKING INTEGER,
CONTACTNO NUMBER(10)
);


#Alter Table
ALTER TABLE PLAYER ADD MATCHESWON NUMBER;

ALTER TABLE PLAYER ADD MATCHESPLAYED NUMBER;
